"""create inference tables

Revision ID: a8e538275d7f
Revises: 
Create Date: 2026-06-14 22:09:36.829746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e538275d7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_browsing_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_type', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_user_browsing_events_client_time', 'user_browsing_events', ['client_id', 'date_time'], unique=False)
    op.create_table('users',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('visit_id', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_user_browsing_events_client_time', table_name='user_browsing_events')
    op.drop_table('user_browsing_events')
    # ### end Alembic commands ###
